config/routes.rb
Rails.application.routes.draw do
  root 'palettes#index'

  post 'palettes/add_colour'

  resources :palettes
  resources :colours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colour.rb
class Colour < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :hex, presence: true, uniqueness: true, format: { with: /#?([A-F0-9]{6}|[A-F0-9]{3})/i, message: "not valid colour" }
  has_and_belongs_to_many :palettes
end

app/models/palette.rb
class Palette < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_and_belongs_to_many :colours
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :find_colour, only: %i[update destroy edit show]

  def index
    @colours = Colour.order('name').page(params[:page]).per(8)
  end

  def new
    @colour = Colour.new
  end

  def show; end

  def edit; end

  def create
    @colour = Colour.new(colour_params)
    if @colour.save
      flash[:success] = 'Color created successfully'
      redirect_to colours_path
    else
      render 'new'
    end
  end

  def update
    if @colour.update(colour_params)
      flash[:success] = 'Color Updated successfully'
      redirect_to @colour
    else
      render 'edit'
    end
  end

  def destroy
    flash[:danger] = 'colour not deleted' unless @colour.destroy
    redirect_to colours_path
  end

  private

  def find_colour
    @colour = Colour.find_by_id(params[:id])
    return if @colour.present?

    flash[:danger] = 'No colour found'
    redirect_to colours_path
  end

  def colour_params
    params.require(:colour).permit(:name, :hex)
  end
end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  before_action :find_palette, only: %i[show edit destroy update]
  before_action :find_color, only: %i[new edit create update]
  before_action :find_palette_color, only: %i[create update]

  def index
    @palettes = Palette.order('id DESC').page(params[:page]).per(6)
  end

  def show; end

  def new
    @palette = Palette.new
  end

  def create
    @palette = Palette.new(palette_params)
    
    if @palette.save
      @palette_colors.each do |color|
        @palette.colours << color
      end
      flash[:success] = 'Palette created successfully'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @palette.update(palette_params)
      
      # remove colours
      colors_to_remove = @palette.colours - @palette_colors
      colors_to_remove.each { |color| @palette.colours.delete color }

      # add new colours
      @palette_colors.each do |colour|
        @palette.colours << colour if !@palette.colours.include? colour
      end

      flash[:success] = 'Palette Updated successfully'
      redirect_to @palette
    else
      render 'edit'
    end
  end

  def destroy
    flash[:success] = 'Palette deleted successfully' if @palette.destroy
    redirect_back(fallback_location: root_url)
  end

  private

  def find_palette
    @palette = Palette.find_by_id(params[:id])
    return if @palette.present?

    flash[:danger] = 'No palette found'
    redirect_to palettes_path
  end

  def find_palette_color
    @palette_colors = Colour.where(id: params[:colour_ids])
    unless @palette_colors.present?
      flash[:error] = 'Please select valid colors'
      render params[action] == 'create' ? 'new' : 'edit' && return
    end
  end

  def find_color
    @colours = Colour.all
  end

  def palette_params
    params.require(:palette).permit(:name, :color_ids)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colours_helper.rb
module ColoursHelper
end

app/helpers/palettes_helper.rb
module PalettesHelper
end

app/views/colours/_box.html.erb
<span style="width: 50px; height: 50px; margin:5px; background: rgb(<%= colour[0] %>, <%= colour[1] %>, <%= colour[2] %>)"></span>

app/views/colours/_form.html.erb
<div id="colour_view" style="width: 250px; height: 40px; border-color: black; border-width: 5px"></div>

<%= form_for @colour do |f| %>
  <div class="form-group">
    <label for="colour_name">Name:</label>
    <%= f.text_field :name , placeholder: 'Enter colour name', class: 'form-control' %>
    <div class="error text-danger">
      <%= @colour.errors[:name][0] %>
    </div>
  </div>

  <div class="form-group">
    <label for="colour_hex">Code:</label>
    <%= f.text_field :hex , placeholder: '#RRGGBB', class: 'form-control', onkeypress: "showColour()" %>
    <span class="error text-danger">
      <%= @colour.errors[:hex][0] %>
    </span>
  </div>

  <%= f.submit save_button, class: "btn btn-success" %><br>
<% end %>

<script>
  function showColour(){
    var code = $("#colour_hex").val();
    $("#colour_view").css("background",code);
  }
</script>

app/views/colours/_list.html.erb
<table class="container table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    <% colours.each do |colour| %>
      <tr>
        <td><%= colour.name %></td>
        <td><%= colour.hex %></td>
        <td style="background: <%= colour.hex %>"></td>
        <td align="right"><%= link_to 'Change', edit_colour_path(colour.id) %></td>
        <td align="right"><%= link_to 'Delete', delete_link, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/colours/create.js.erb
$("#message").html("Colour <%= @colour.hex %> created");

app/views/colours/edit.html.erb
<center><h3 style="color: #faa">Colour Creator</h3></center>
<div class = "body" style = "margin-left: 10px">
  <p>
    <%= link_to 'Create palette', new_palette_path %>
  </p>

  <div>
    <%= render 'form', save_button: 'Update' %>
  </div>
  </center>
</div>

app/views/colours/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-home" href="/palettes">Home</a>
    </div>
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-plus" href="colours/new">New Colour</a>
      <a class="nav-item nav-link fa fa-plus" href="/palettes/new">New Palette</a>
    </div>
  </div>
</nav>
<br>

<h3 align="center" class="text-secondary"> All Colours </h3>
<br>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="pull-right"><%= page_entries_info @colours %></div>
<table class="container table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    <% @colours.each do |colour| %>
      <tr>
        <td><%= colour.name %></td>
        <td><%= colour.hex %></td>
        <td style="background: <%= colour.hex %>"></td>
        <td align="right"><%= link_to 'Change', edit_colour_path(colour.id) %></td>
        <td align="right"><%= link_to 'Delete', colour_path(colour.id), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="pagination">
  <%= paginate @colours, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm",              nav_class: "d-inline-b" %>
</div>    

app/views/colours/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-home" href="/palettes">Home</a>
    </div>
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-list-alt" href="/colours">Colours</a>
      <a class="nav-item nav-link fa fa-plus" href="/palettes/new">New Palette</a>
    </div>
  </div>
</nav>
<br>

<center><h3 style="color: #faa">Colour Creator</h3></center>

<div class = "body">

  <div >
      <%= render 'form', save_button: 'Add' %>
  </div>
</div>

app/views/colours/no_colour.html.erb
<center id="invalid_record">
  <b>No Such Colour</b><br>
  <%= link_to 'Go To Home', root_url, class: "fa fa-home" %>
</center>

app/views/colours/show.html.erb
<h3 class="text-secondary">Colour Info:</h3>
<div class = "body">
  <p>
    <%= link_to '< Go to Home', palettes_path %>
  </p>

  <div >
    <div id="preview" style="background: <%= @colour.hex %>"></div><br>
    Name: <%= @colour.name %><br>
    Code: <%= @colour.hex %>
  </div>
  <br>
  <%= link_to 'Change', edit_colour_path(@colour.id) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaletteTool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/palettes/_form.html.erb
<div class="card container body" id="palette">
  <div class="card-body">
    <%= form_for @palette do |f| %>
      <p>
        <label for="name"><b>Name</b></label><br>
        <%= f.text_field :name %>
        <div class="error text-danger">
          <%= @palette.errors[:name][0] %>
        </div>
      </p>
      <p>
        <label for="selection"><b>Choose Colours</b></label>
        <%= select_tag 'colour_ids', options_for_select(@colours.collect {|a| [a.name, a.id]}, @palette.colours.pluck(:id)), {multiple: true, class: 'select2', id: "selection", required: true} %>
      </p>

      <%= f.submit save_button, class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/palettes/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-home" href="/palettes">Home</a>
    </div>
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-plus" href="/colours/new">New Colour</a>
      <a class="nav-item nav-link fa fa-plus" href="/palettes/new">New Palette</a>
    </div>
  </div>
</nav>
<br>

<h3 align="center" class="shadow"><b>Palette: <%= @palette.name %></b></h3>
<br>

<%= render 'form', colours: @colours, save_button: 'Update' %>

<script>
  $('#selection').select2({
    theme: "bootstrap"
  });
</script>

app/views/palettes/index.html.erb
<nav class="nav navbar bg-light">
  <div class="nav navbar-brand"><b>Palettes</b></div>
  <div class="nav">
    <%= link_to 'Colours', colours_path, class: "nav-link nav-item btn btn-danger", style: "margin-right: 10px" %>
    <%= link_to 'New Palette', new_palette_path, class: "nav-link nav-item btn btn-info" %>
  </div>
</nav>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="pull-right"><%= page_entries_info @palettes %></div>
<table id = "palettes" class="table container panel panel-default" >
  <% if @palettes.empty? %>
    No Palettes to show
  <% else %>
    <thead>
      <tr>
        <th>Name</th>
        <th>Colours</th>
        <th>Action</th>
      </tr>
    </thead>
    <% @palettes.each do |palette| %>
      <tr>
        <td><%= link_to "#{palette.name}", palette_path(id: palette.id) %></td>
        <td>
          <div id="swatches">
            <% palette.colours.each do |colour| %>
              <span id="swatch" style="background: <%= colour.hex %>">
              </span>
            <% end %>    
          </div>
        </td>
        <td>
          <a href=<%= edit_palette_path(id: palette.id) %> ><i class="fa fa-edit"></i></a>
          <a href=<%= palette_path(id: palette.id) %> data-method="delete"><i class="fa fa-trash"></i></a>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>
<div id="pagination">
  <%= paginate @palettes, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm",              nav_class: "d-inline-b" %>
</div>

app/views/palettes/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-home" href="/palettes">Home</a>
    </div>
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-plus" href="/colours/new">New Colour</a>
    </div>
  </div>
</nav>
<br>

<h3 align="center" class="shadow"><b>Create a new Palette</b></h3>

<%= render 'form', colours: @colours, save_button: 'Create Palette' %>

<script>
  $('#selection').select2({
    theme: "bootstrap"
  });
</script>

app/views/palettes/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-home" href="/palettes">Home</a>
    </div>
    <div class="nav navbar-nav">
      <a class="nav-item nav-link fa fa-plus" href="/colours/new">New Colour</a>
      <a class="nav-item nav-link fa fa-plus" href="/palettes/new">New Palette</a>
    </div>
  </div>
</nav>
<br>

<h3 align="center" class="shadow"><b>Palette: <%= @palette.name %></b></h3>
<br>

<table class="table container">
  <thead>
    <tr>
      <th>Colour</th>
      <th>Code</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    <% @palette.colours.each do |colour| %>
      <tr>
        <td><%= colour.name %></td>
        <td><%= colour.hex %></td>
        <td style="background: <%= colour.hex %>"></td>
      </tr>
    <% end %>
  </tbody>
</table>